net: netcp: correct netcp_get_stats function signature
Commit: 0ab3f2f6cd7f - net: make ndo_get_stats64 a void function
and
Commit: fd917a5aebfe - net: netcp: store network statistics in 64 bits.

The commit fd917a5aebfe adds ndo_get_stats64 function as per old
signature which causes compilation error:

drivers/net/ethernet/ti/netcp_core.c:1951:28: error:
initialization from incompatible pointer type
  .ndo_get_stats64        = netcp_get_stats,

Hence correct netcp_get_stats function signature as per
the latest definition.

Signed-off-by: Keerthy <j-keerthy@ti.com>
Fixes: fd917a5aebfe7368 ("net: netcp: store network statistics in 64 bits")
Signed-off-by: David S. Miller <davem@davemloft.net>