scr24x_cs: include linux/io.h
The newly added scr24x_cs driver doesn't build in some configurations:

drivers/char/pcmcia/scr24x_cs.c: In function 'scr24x_wait_ready':
drivers/char/pcmcia/scr24x_cs.c:76:12: error: implicit declaration of function 'ioread8' [-Werror=implicit-function-declaration]

Adding in explicit include for the right header makes it work.

Fixes: f95d960b9949 ("char/pcmcia: add scr24x_cs chip card interface driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>