soc: qcom: secure_buffer: change the way of divide
When compile kernel, we will get the following error:
	undefined reference to `__aeabi_uldivmod'
So we change the way of divide.

Change-Id: I632ea6778bc4e6e881a327c81e2e8650725388b0
Signed-off-by: Tengfei Fan <tengfeif@codeaurora.org>