Revert "net: dccp: initialize (addr,port) listening hashtable"
This reverts commit 74dc7f3385b8fa8c097c066aa01163211739cd7b.

Cause build failures when DCCP is modular.

ERROR: "inet_hashinfo2_init" [net/dccp/dccp.ko] undefined!

Signed-off-by: David S. Miller <davem@davemloft.net>