ARM: imx: drop CPUIDLE_FLAG_TIME_VALID from cpuidle-imx6sx
As the result of commit 0291b64140c4 ("cpuidle: Invert
CPUIDLE_FLAG_TIME_VALID logic"), the flag gets removed and hence we see
the compile error below.

  CC      arch/arm/mach-imx/cpuidle-imx6sx.o
arch/arm/mach-imx/cpuidle-imx6sx.c:69:13: error: ‘CPUIDLE_FLAG_TIME_VALID’ undeclared here (not in a function)

Since the behavior of the original flag has been the default, we can
simply drop the flag now.

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Shawn Guo <shawn.guo@linaro.org>