ANDROID: drm/msm/a6xx: Make a6xx_gmu_bo.iova a dma_addr_t
With commit 46c50548dcc5 ("FROMLIST: drm/msm/a6xx: Use the DMA
API for GMU memory objects") it started using the iova entry in
the a6xx_gmu_bo structure as a dma_attr_t. Unfortunately this
runs into type trouble on 32 bit platforms.

Specifically:
  drivers/gpu/drm/msm/adreno/a6xx_gmu.c:943:49: error: passing
  argument 3 of ‘dma_alloc_attrs’ from incompatible pointer type
  [-Werror=incompatible-pointer-types]

as reported by kernelci:
https://kernelci.org/build/id/5e552216959c29be1c5ea41a/logs/

So this patch changes the type of iova to dma_addr_t to fix
these build issues.

Fixes: 46c50548dcc5 ("FROMLIST: drm/msm/a6xx: Use the DMA API for GMU memory objects")
Signed-off-by: John Stultz <john.stultz@linaro.org>
Change-Id: Ia3a76acc1d501c629508bf4d10a931353a49568d